import * as accordion from './accordion/index';
import * as fieldset from './fieldset/index';
import * as fileUpload from './file-upload/index';
import * as slider from './slider/index';
import * as autocomplete from './autocomplete/index';
import * as badge from './badge/index';
import * as breadcrumb from './breadcrumb/index';
import * as button from './button/index';
import * as card from './card/index';
import * as checkbox from './checkbox/index';
import * as chip from './chip/index';
import * as chipGroup from './chip-group/index';
import * as inputDate from './input-date/index';
import * as inputNumber from './input-number/index';
import * as inputText from './input-text/index';
import * as link from './link/index';
import * as list from './list/index';
import * as menu from './menu/index';
import * as message from './message/index';
import * as pagination from './pagination/index';
import * as popover from './popover/index';
import * as progress from './progress/index';
import * as dialog from './dialog/index';
import * as divider from './divider/index';
import * as emptyState from './empty-state/index';
import * as formField from './form-field/index';
import * as icon from './icon/index';
import * as radioGroup from './radio-group/index';
import * as select from './select/index';
import * as skeleton from './skeleton/index';
import * as spinner from './spinner/index';
import * as snackbar from './snackbar/index';
import * as switchMod from './switch/index';
import * as table from './table/index';
import * as tabs from './tabs/index';
import * as textarea from './textarea/index';
import * as tooltip from './tooltip/index';
import * as tokens from './tokens/index';

describe('library barrel exports', () => {
  it('re-exports all public components', () => {
    expect(autocomplete.AuAutocomplete).toBeDefined();
    expect(accordion.AuAccordion).toBeDefined();
    expect(accordion.AuAccordionItem).toBeDefined();
    expect(accordion.AuAccordionPanel).toBeDefined();
    expect(badge.AuBadge).toBeDefined();
    expect(breadcrumb.AuBreadcrumb).toBeDefined();
    expect(button.AuButton).toBeDefined();
    expect(card.AuCard).toBeDefined();
    expect(card.AuCardFooter).toBeDefined();
    expect(checkbox.AuCheckbox).toBeDefined();
    expect(chip.AuChip).toBeDefined();
    expect(chipGroup.AuChipGroup).toBeDefined();
    expect(inputDate.AuInputDate).toBeDefined();
    expect(inputNumber.AuInputNumber).toBeDefined();
    expect(inputText.AuInputText).toBeDefined();
    expect(link.AuLink).toBeDefined();
    expect(list.AuList).toBeDefined();
    expect(menu.AuMenu).toBeDefined();
    expect(menu.AuMenuItem).toBeDefined();
    expect(menu.AuMenuTrigger).toBeDefined();
    expect(list.AuListItem).toBeDefined();
    expect(message.AuMessage).toBeDefined();
    expect(pagination.AuPagination).toBeDefined();
    expect(popover.AuPopover).toBeDefined();
    expect(popover.AuPopoverTrigger).toBeDefined();
    expect(progress.AuProgress).toBeDefined();
    expect(dialog.AuDialog).toBeDefined();
    expect(divider.AuDivider).toBeDefined();
    expect(emptyState.AuEmptyState).toBeDefined();
    expect(emptyState.AuEmptyStateMedia).toBeDefined();
    expect(fieldset.AuFieldset).toBeDefined();
    expect(fileUpload.AuFileUpload).toBeDefined();
    expect(formField.AuFormField).toBeDefined();
    expect(icon.AuIcon).toBeDefined();
    expect(dialog.AuDialogFooter).toBeDefined();
    expect(radioGroup.AuRadioGroup).toBeDefined();
    expect(select.AuSelect).toBeDefined();
    expect(skeleton.AuSkeleton).toBeDefined();
    expect(slider.AuSlider).toBeDefined();
    expect(spinner.AuSpinner).toBeDefined();
    expect(snackbar.AuSnackbar).toBeDefined();
    expect(switchMod.AuSwitch).toBeDefined();
    expect(table.AuTable).toBeDefined();
    expect(table.AuTableColumn).toBeDefined();
    expect(table.AuTableCellDef).toBeDefined();
    expect(tabs.AuTabs).toBeDefined();
    expect(tabs.AuTab).toBeDefined();
    expect(tabs.AuTabPanel).toBeDefined();
    expect(textarea.AuTextarea).toBeDefined();
    expect(tooltip.AuTooltip).toBeDefined();
    expect(tokens.AuTheme).toBeDefined();
    expect(tokens.AuDensityDirective).toBeDefined();
  });
});
