/** All registered `au-icon` glyph names (stable API surface). */
export const AU_ICON_NAMES = [
  'check-circle',
  'check',
  'warning',
  'error',
  'info',
  'close',
  'spinner',
  'chevron-down',
  'chevron-up',
  'chevron-left',
  'chevron-right',
  'sort-asc',
  'sort-desc',
  'sort-neutral',
  'calendar',
  'clock',
  'search',
  'plus',
  'minus',
  'eye',
  'eye-off',
  'menu',
  'more-vertical',
  'arrow-left',
  'arrow-right',
  'bell',
  'circle-help',
  'settings',
  'trash-2',
  'house',
  'users',
  'mail',
  'megaphone',
  'clipboard-check',
  'clipboard-list',
  'building-2',
  'file-text',
  'file-badge',
  'heart-handshake',
  'compass',
  'file-pen-line',
  'trophy',
  'book-open',
  'utensils-crossed',
  'folder-open',
  'chart-column',
  'graduation-cap',
  'user-plus',
  'door-open',
  'key-round',
  'door-closed',
  'calendar-days',
  'layout-grid',
  'grip-vertical',
  'star',
] as const;

export type AuIconName = (typeof AU_ICON_NAMES)[number];

export type AuIconSize = 'xs' | 'sm' | 'md' | 'lg';
