/** Generated by scripts/sync-visual-stories.mjs — do not edit manually. */
export const VISUAL_STORIES: {
  readonly name: string;
  readonly id: string;
  readonly slug: string;
}[] = [
  { name: 'badge-variants', id: 'aurea-badge--variants', slug: 'badge' },
  { name: 'breadcrumb-default', id: 'aurea-breadcrumb--default', slug: 'breadcrumb' },
  { name: 'button-primary', id: 'aurea-button--primary', slug: 'button' },
  { name: 'card-default', id: 'aurea-card--default', slug: 'card' },
  { name: 'checkbox-default', id: 'aurea-checkbox--default', slug: 'checkbox' },
  { name: 'chip-default', id: 'aurea-chip--default', slug: 'chip' },
  { name: 'dialog-default', id: 'aurea-dialog--default', slug: 'dialog' },
  { name: 'divider-default', id: 'aurea-divider--default', slug: 'divider' },
  { name: 'form-field-with-input', id: 'aurea-form-field--with-input', slug: 'form-field' },
  { name: 'icon-default', id: 'aurea-icon--default', slug: 'icon' },
  { name: 'input-number-default', id: 'aurea-input-number--default', slug: 'input-number' },
  { name: 'input-text-default', id: 'aurea-inputtext--default', slug: 'input-text' },
  { name: 'link-default', id: 'aurea-link--default', slug: 'link' },
  { name: 'menu-default', id: 'aurea-menu--default', slug: 'menu' },
  { name: 'message-success', id: 'aurea-message--success', slug: 'message' },
  { name: 'pagination-default', id: 'aurea-pagination--default', slug: 'pagination' },
  { name: 'popover-filters', id: 'aurea-popover--filters', slug: 'popover' },
  { name: 'progress-determinate', id: 'aurea-progress--determinate', slug: 'progress' },
  { name: 'radio-group-default', id: 'aurea-radio-group--default', slug: 'radio-group' },
  { name: 'select-default', id: 'aurea-select--default', slug: 'select' },
  { name: 'skeleton-text', id: 'aurea-skeleton--text', slug: 'skeleton' },
  { name: 'snackbar-default', id: 'aurea-snackbar--default', slug: 'snackbar' },
  { name: 'switch-default', id: 'aurea-switch--default', slug: 'switch' },
  { name: 'table-default', id: 'aurea-table--default', slug: 'table' },
  { name: 'textarea-default', id: 'aurea-textarea--default', slug: 'textarea' },
  { name: 'tooltip-default', id: 'aurea-tooltip--default', slug: 'tooltip' },
];
