/**
 * Storybook story id prefixes for **stable** components (axe-core CI).
 * Slugs match folder names under src/lib/ and COMPONENT_MATURITY.
 */
export const STABLE_STORY_PREFIXES = [
  'aurea-accordion--',
  'aurea-autocomplete--',
  'aurea-avatar--',
  'aurea-badge--',
  'aurea-breadcrumb--',
  'aurea-button--',
  'aurea-buttongroup--',
  'aurea-card--',
  'aurea-checkbox--',
  'aurea-chip--',
  'aurea-chipgroup--',
  'aurea-dialog--',
  'aurea-descriptionlist--',
  'aurea-divider--',
  'aurea-drawer--',
  'aurea-emptystate--',
  'aurea-fieldset--',
  'aurea-fileupload--',
  'aurea-formfield--',
  'aurea-icon--',
  'aurea-inputdate--',
  'aurea-inputnumber--',
  'aurea-inputpassword--',
  'aurea-inputtime--',
  'aurea-inputtext--',
  'aurea-link--',
  'aurea-list--',
  'aurea-menu--',
  'aurea-message--',
  'aurea-popover--',
  'aurea-table--',
  'aurea-pagination--',
  'aurea-progress--',
  'aurea-radiogroup--',
  'aurea-select--',
  'aurea-skeleton--',
  'aurea-slider--',
  'aurea-snackbar--',
  'aurea-spinner--',
  'aurea-steps--',
  'aurea-switch--',
  'aurea-tabs--',
  'aurea-taginput--',
  'aurea-textarea--',
  'aurea-tooltip--',
] as const;

export function isStableStoryId(storyId: string): boolean {
  return STABLE_STORY_PREFIXES.some((prefix) => storyId.startsWith(prefix));
}
